export const UPDATE_TODO_LIST_FILTER = 'UPDATE_TODO_LIST_FILTER';
export const ADD_CATEGORY_TODO = 'ADD_CATEGORY_TODO';
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS';
export const UPDATE_TODO = 'UPDATE_TODO';
export const MOVE_TODO_INTO_CATEGORY = 'MOVE_TODO_INTO_CATEGORY';
